<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MININT-VK4UT2B" failures="1" tests="5" name="Run_Scenario1" time="49.504" errors="0" timestamp="2024-12-29T18:57:06 CET" skipped="0">
  <testcase classname="Run_Scenario1" name="runScenario" time="9.624"/>
  <testcase classname="Run_Scenario1" name="runScenario" time="9.520"/>
  <testcase classname="Run_Scenario1" name="runScenario" time="9.240"/>
  <testcase classname="Run_Scenario1" name="runScenario" time="10.485">
    <failure message="The success message is incorrect. expected [Congratulations! Your new account has been successfully created!] but found [If you already have an account with us, please login at the login page.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The success message is incorrect. expected [Congratulations! Your new account has been successfully created!] but found [If you already have an account with us, please login at the login page.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at steps.Steps_Scenario1.theUserShouldSeeAConfirmationMessage(Steps_Scenario1.java:75)
at âœ½.the user should see a confirmation message(file:///C:/Users/jacot/Documents/GitHub/PerformingTest/src/test/java/features/F1.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Run_Scenario1" name="runScenario" time="10.635"/>
</testsuite> <!-- Run_Scenario1 -->
