<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BJ5NU7R" failures="1" tests="1" name="Run_Feature1" time="5.441" errors="0" timestamp="2024-12-20T16:50:46 CET" skipped="0">
  <testcase classname="Run_Feature1" name="runScenario" time="5.441">
    <failure message="The success message is incorrect. expected [Congratulations! Your new account has been successfully created!] but found [If you already have an account with us, please login at the login page.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The success message is incorrect. expected [Congratulations! Your new account has been successfully created!] but found [If you already have an account with us, please login at the login page.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at steps.Steps_Feature1.theUserShouldSeeAConfirmationMessage(Steps_Feature1.java:55)
at âœ½.the user should see a confirmation message(file:///C:/Users/David%20Bonilla/OneDrive/Escritorio/Universidad/4t%20curs%20universitari/1r%20semestre/Test%20i%20Qualitat%20del%20Software%20(TQS)/Proyecto/Segunda%20practica/PerformingTest/src/test/java/features/F1.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Run_Feature1 -->
